// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.7.1
// source: protos/beacons_v1.proto

package beacons_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type          string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Category      string            `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Code          string            `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CorrelationId string            `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Status        string            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Message       string            `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Cause         string            `protobuf:"bytes,7,opt,name=cause,proto3" json:"cause,omitempty"`
	StackTrace    string            `protobuf:"bytes,8,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Details       map[string]string `protobuf:"bytes,9,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ErrorDescription) Reset() {
	*x = ErrorDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDescription) ProtoMessage() {}

func (x *ErrorDescription) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDescription.ProtoReflect.Descriptor instead.
func (*ErrorDescription) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDescription) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ErrorDescription) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ErrorDescription) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDescription) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ErrorDescription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ErrorDescription) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDescription) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *ErrorDescription) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *ErrorDescription) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type PagingParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skip  int64 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take  int32 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	Total bool  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *PagingParams) Reset() {
	*x = PagingParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PagingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagingParams) ProtoMessage() {}

func (x *PagingParams) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagingParams.ProtoReflect.Descriptor instead.
func (*PagingParams) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{1}
}

func (x *PagingParams) GetSkip() int64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *PagingParams) GetTake() int32 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *PagingParams) GetTotal() bool {
	if x != nil {
		return x.Total
	}
	return false
}

type InternalArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InternalArray []float32 `protobuf:"fixed32,1,rep,packed,name=internal_array,json=internalArray,proto3" json:"internal_array,omitempty"`
}

func (x *InternalArray) Reset() {
	*x = InternalArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalArray) ProtoMessage() {}

func (x *InternalArray) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalArray.ProtoReflect.Descriptor instead.
func (*InternalArray) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{2}
}

func (x *InternalArray) GetInternalArray() []float32 {
	if x != nil {
		return x.InternalArray
	}
	return nil
}

type GeoPointV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string           `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Coordinates []*InternalArray `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *GeoPointV1) Reset() {
	*x = GeoPointV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoPointV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPointV1) ProtoMessage() {}

func (x *GeoPointV1) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPointV1.ProtoReflect.Descriptor instead.
func (*GeoPointV1) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{3}
}

func (x *GeoPointV1) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GeoPointV1) GetCoordinates() []*InternalArray {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type BeaconV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SiteId string      `protobuf:"bytes,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Type   string      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Udi    string      `protobuf:"bytes,4,opt,name=udi,proto3" json:"udi,omitempty"`
	Label  string      `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	Center *GeoPointV1 `protobuf:"bytes,6,opt,name=center,proto3" json:"center,omitempty"`
	Radius float32     `protobuf:"fixed32,8,opt,name=radius,proto3" json:"radius,omitempty"`
}

func (x *BeaconV1) Reset() {
	*x = BeaconV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconV1) ProtoMessage() {}

func (x *BeaconV1) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconV1.ProtoReflect.Descriptor instead.
func (*BeaconV1) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{4}
}

func (x *BeaconV1) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BeaconV1) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *BeaconV1) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BeaconV1) GetUdi() string {
	if x != nil {
		return x.Udi
	}
	return ""
}

func (x *BeaconV1) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BeaconV1) GetCenter() *GeoPointV1 {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *BeaconV1) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type BeaconV1Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data  []*BeaconV1 `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BeaconV1Page) Reset() {
	*x = BeaconV1Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconV1Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconV1Page) ProtoMessage() {}

func (x *BeaconV1Page) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconV1Page.ProtoReflect.Descriptor instead.
func (*BeaconV1Page) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{5}
}

func (x *BeaconV1Page) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BeaconV1Page) GetData() []*BeaconV1 {
	if x != nil {
		return x.Data
	}
	return nil
}

// The request message containing the beacon page request.
type BeaconV1PageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string            `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Filter        map[string]string `protobuf:"bytes,2,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Paging        *PagingParams     `protobuf:"bytes,3,opt,name=paging,proto3" json:"paging,omitempty"`
}

func (x *BeaconV1PageRequest) Reset() {
	*x = BeaconV1PageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconV1PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconV1PageRequest) ProtoMessage() {}

func (x *BeaconV1PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconV1PageRequest.ProtoReflect.Descriptor instead.
func (*BeaconV1PageRequest) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{6}
}

func (x *BeaconV1PageRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BeaconV1PageRequest) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *BeaconV1PageRequest) GetPaging() *PagingParams {
	if x != nil {
		return x.Paging
	}
	return nil
}

// The response message containing the beacon page response
type BeaconV1PageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ErrorDescription `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Page  *BeaconV1Page     `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *BeaconV1PageReply) Reset() {
	*x = BeaconV1PageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconV1PageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconV1PageReply) ProtoMessage() {}

func (x *BeaconV1PageReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconV1PageReply.ProtoReflect.Descriptor instead.
func (*BeaconV1PageReply) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{7}
}

func (x *BeaconV1PageReply) GetError() *ErrorDescription {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *BeaconV1PageReply) GetPage() *BeaconV1Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// The request message containing the beacon id request.
type BeaconV1IdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	BeaconId      string `protobuf:"bytes,2,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
}

func (x *BeaconV1IdRequest) Reset() {
	*x = BeaconV1IdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconV1IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconV1IdRequest) ProtoMessage() {}

func (x *BeaconV1IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconV1IdRequest.ProtoReflect.Descriptor instead.
func (*BeaconV1IdRequest) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{8}
}

func (x *BeaconV1IdRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BeaconV1IdRequest) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

// The request message containing the beacon udi request.
type BeaconV1UdiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	BeaconUdi     string `protobuf:"bytes,2,opt,name=beacon_udi,json=beaconUdi,proto3" json:"beacon_udi,omitempty"`
}

func (x *BeaconV1UdiRequest) Reset() {
	*x = BeaconV1UdiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconV1UdiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconV1UdiRequest) ProtoMessage() {}

func (x *BeaconV1UdiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconV1UdiRequest.ProtoReflect.Descriptor instead.
func (*BeaconV1UdiRequest) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{9}
}

func (x *BeaconV1UdiRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BeaconV1UdiRequest) GetBeaconUdi() string {
	if x != nil {
		return x.BeaconUdi
	}
	return ""
}

// The request message containing the beacon position request.
type BeaconV1PositionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string   `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Udis          []string `protobuf:"bytes,2,rep,name=udis,proto3" json:"udis,omitempty"`
	SiteId        string   `protobuf:"bytes,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
}

func (x *BeaconV1PositionRequest) Reset() {
	*x = BeaconV1PositionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconV1PositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconV1PositionRequest) ProtoMessage() {}

func (x *BeaconV1PositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconV1PositionRequest.ProtoReflect.Descriptor instead.
func (*BeaconV1PositionRequest) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{10}
}

func (x *BeaconV1PositionRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BeaconV1PositionRequest) GetUdis() []string {
	if x != nil {
		return x.Udis
	}
	return nil
}

func (x *BeaconV1PositionRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

// The request message containing the beacon object request.
type BeaconV1ObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string    `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Beacon        *BeaconV1 `protobuf:"bytes,2,opt,name=beacon,proto3" json:"beacon,omitempty"`
}

func (x *BeaconV1ObjectRequest) Reset() {
	*x = BeaconV1ObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconV1ObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconV1ObjectRequest) ProtoMessage() {}

func (x *BeaconV1ObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconV1ObjectRequest.ProtoReflect.Descriptor instead.
func (*BeaconV1ObjectRequest) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{11}
}

func (x *BeaconV1ObjectRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BeaconV1ObjectRequest) GetBeacon() *BeaconV1 {
	if x != nil {
		return x.Beacon
	}
	return nil
}

// The response message containing the beacon object response
type BeaconV1ObjectReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error  *ErrorDescription `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Beacon *BeaconV1         `protobuf:"bytes,2,opt,name=beacon,proto3" json:"beacon,omitempty"`
}

func (x *BeaconV1ObjectReply) Reset() {
	*x = BeaconV1ObjectReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconV1ObjectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconV1ObjectReply) ProtoMessage() {}

func (x *BeaconV1ObjectReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconV1ObjectReply.ProtoReflect.Descriptor instead.
func (*BeaconV1ObjectReply) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{12}
}

func (x *BeaconV1ObjectReply) GetError() *ErrorDescription {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *BeaconV1ObjectReply) GetBeacon() *BeaconV1 {
	if x != nil {
		return x.Beacon
	}
	return nil
}

//  The response message containing the geo point object response
type BeaconV1PositionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ErrorDescription `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Point *GeoPointV1       `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
}

func (x *BeaconV1PositionReply) Reset() {
	*x = BeaconV1PositionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_beacons_v1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconV1PositionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconV1PositionReply) ProtoMessage() {}

func (x *BeaconV1PositionReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_beacons_v1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconV1PositionReply.ProtoReflect.Descriptor instead.
func (*BeaconV1PositionReply) Descriptor() ([]byte, []int) {
	return file_protos_beacons_v1_proto_rawDescGZIP(), []int{13}
}

func (x *BeaconV1PositionReply) GetError() *ErrorDescription {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *BeaconV1PositionReply) GetPoint() *GeoPointV1 {
	if x != nil {
		return x.Point
	}
	return nil
}

var File_protos_beacons_v1_proto protoreflect.FileDescriptor

var file_protos_beacons_v1_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73,
	0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x62, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x73, 0x5f, 0x76, 0x31, 0x22, 0xe7, 0x02, 0x0a, 0x10, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x43,
	0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x29, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x4c, 0x0a, 0x0c, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73,
	0x6b, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x36, 0x0a,
	0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x25,
	0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x22, 0x5d, 0x0a, 0x0a, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x56, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62,
	0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x08, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56,
	0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x64, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x64, 0x69,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x2e, 0x0a, 0x06, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73,
	0x5f, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x56, 0x31, 0x52, 0x06,
	0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x22, 0x4e,
	0x0a, 0x0c, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x50, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e,
	0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xee,
	0x01, 0x0a, 0x13, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x50, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x43, 0x0a,
	0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x56, 0x31, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e,
	0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x67, 0x1a, 0x39, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x75, 0x0a, 0x11, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x50, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2c, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73,
	0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x50, 0x61, 0x67, 0x65,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x57, 0x0a, 0x11, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e,
	0x56, 0x31, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63,
	0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x5a, 0x0a, 0x12, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x55, 0x64, 0x69, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x75, 0x64, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x55, 0x64, 0x69, 0x22, 0x6d, 0x0a, 0x17, 0x42,
	0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x64, 0x69, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x64, 0x69,
	0x73, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x22, 0x6c, 0x0a, 0x15, 0x42, 0x65,
	0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x62, 0x65,
	0x61, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x65, 0x61,
	0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31,
	0x52, 0x06, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x22, 0x77, 0x0a, 0x13, 0x42, 0x65, 0x61, 0x63,
	0x6f, 0x6e, 0x56, 0x31, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x32, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x2c, 0x0a, 0x06, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31,
	0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x52, 0x06, 0x62, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x22, 0x79, 0x0a, 0x15, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x65, 0x61, 0x63,
	0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2c,
	0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6f, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x56, 0x31, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0xf1, 0x04, 0x0a,
	0x09, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x56, 0x31, 0x12, 0x4f, 0x0a, 0x0b, 0x67, 0x65,
	0x74, 0x5f, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x2e, 0x62, 0x65, 0x61, 0x63,
	0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x62, 0x65, 0x61,
	0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x10, 0x67,
	0x65, 0x74, 0x5f, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x12,
	0x1d, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61,
	0x63, 0x6f, 0x6e, 0x56, 0x31, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63,
	0x6f, 0x6e, 0x56, 0x31, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x55, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x65, 0x61, 0x63,
	0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e,
	0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f,
	0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0d, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x62, 0x65, 0x61, 0x63,
	0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62,
	0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e,
	0x56, 0x31, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x57, 0x0a, 0x13, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e,
	0x5f, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x12, 0x1d, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73,
	0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f,
	0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x11, 0x67, 0x65, 0x74, 0x5f,
	0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x62, 0x79, 0x5f, 0x75, 0x64, 0x69, 0x12, 0x1e, 0x2e,
	0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x56, 0x31, 0x55, 0x64, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x56, 0x31, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x5e, 0x0a, 0x12, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73,
	0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56, 0x31, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x65,
	0x61, 0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x56,
	0x31, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x42, 0x0a, 0x1d, 0x70, 0x69, 0x70, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x31, 0x42, 0x0e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x56,
	0x31, 0x50, 0x01, 0xa2, 0x02, 0x0e, 0x42, 0x45, 0x41, 0x43, 0x4f, 0x4e, 0x53, 0x5f, 0x43, 0x4d,
	0x44, 0x5f, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_beacons_v1_proto_rawDescOnce sync.Once
	file_protos_beacons_v1_proto_rawDescData = file_protos_beacons_v1_proto_rawDesc
)

func file_protos_beacons_v1_proto_rawDescGZIP() []byte {
	file_protos_beacons_v1_proto_rawDescOnce.Do(func() {
		file_protos_beacons_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_beacons_v1_proto_rawDescData)
	})
	return file_protos_beacons_v1_proto_rawDescData
}

var file_protos_beacons_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_protos_beacons_v1_proto_goTypes = []interface{}{
	(*ErrorDescription)(nil),        // 0: beacons_v1.ErrorDescription
	(*PagingParams)(nil),            // 1: beacons_v1.PagingParams
	(*InternalArray)(nil),           // 2: beacons_v1.InternalArray
	(*GeoPointV1)(nil),              // 3: beacons_v1.GeoPointV1
	(*BeaconV1)(nil),                // 4: beacons_v1.BeaconV1
	(*BeaconV1Page)(nil),            // 5: beacons_v1.BeaconV1Page
	(*BeaconV1PageRequest)(nil),     // 6: beacons_v1.BeaconV1PageRequest
	(*BeaconV1PageReply)(nil),       // 7: beacons_v1.BeaconV1PageReply
	(*BeaconV1IdRequest)(nil),       // 8: beacons_v1.BeaconV1IdRequest
	(*BeaconV1UdiRequest)(nil),      // 9: beacons_v1.BeaconV1UdiRequest
	(*BeaconV1PositionRequest)(nil), // 10: beacons_v1.BeaconV1PositionRequest
	(*BeaconV1ObjectRequest)(nil),   // 11: beacons_v1.BeaconV1ObjectRequest
	(*BeaconV1ObjectReply)(nil),     // 12: beacons_v1.BeaconV1ObjectReply
	(*BeaconV1PositionReply)(nil),   // 13: beacons_v1.BeaconV1PositionReply
	nil,                             // 14: beacons_v1.ErrorDescription.DetailsEntry
	nil,                             // 15: beacons_v1.BeaconV1PageRequest.FilterEntry
}
var file_protos_beacons_v1_proto_depIdxs = []int32{
	14, // 0: beacons_v1.ErrorDescription.details:type_name -> beacons_v1.ErrorDescription.DetailsEntry
	2,  // 1: beacons_v1.GeoPointV1.coordinates:type_name -> beacons_v1.InternalArray
	3,  // 2: beacons_v1.BeaconV1.center:type_name -> beacons_v1.GeoPointV1
	4,  // 3: beacons_v1.BeaconV1Page.data:type_name -> beacons_v1.BeaconV1
	15, // 4: beacons_v1.BeaconV1PageRequest.filter:type_name -> beacons_v1.BeaconV1PageRequest.FilterEntry
	1,  // 5: beacons_v1.BeaconV1PageRequest.paging:type_name -> beacons_v1.PagingParams
	0,  // 6: beacons_v1.BeaconV1PageReply.error:type_name -> beacons_v1.ErrorDescription
	5,  // 7: beacons_v1.BeaconV1PageReply.page:type_name -> beacons_v1.BeaconV1Page
	4,  // 8: beacons_v1.BeaconV1ObjectRequest.beacon:type_name -> beacons_v1.BeaconV1
	0,  // 9: beacons_v1.BeaconV1ObjectReply.error:type_name -> beacons_v1.ErrorDescription
	4,  // 10: beacons_v1.BeaconV1ObjectReply.beacon:type_name -> beacons_v1.BeaconV1
	0,  // 11: beacons_v1.BeaconV1PositionReply.error:type_name -> beacons_v1.ErrorDescription
	3,  // 12: beacons_v1.BeaconV1PositionReply.point:type_name -> beacons_v1.GeoPointV1
	6,  // 13: beacons_v1.BeaconsV1.get_beacons:input_type -> beacons_v1.BeaconV1PageRequest
	8,  // 14: beacons_v1.BeaconsV1.get_beacon_by_id:input_type -> beacons_v1.BeaconV1IdRequest
	11, // 15: beacons_v1.BeaconsV1.create_beacon:input_type -> beacons_v1.BeaconV1ObjectRequest
	11, // 16: beacons_v1.BeaconsV1.update_beacon:input_type -> beacons_v1.BeaconV1ObjectRequest
	8,  // 17: beacons_v1.BeaconsV1.delete_beacon_by_id:input_type -> beacons_v1.BeaconV1IdRequest
	9,  // 18: beacons_v1.BeaconsV1.get_beacon_by_udi:input_type -> beacons_v1.BeaconV1UdiRequest
	10, // 19: beacons_v1.BeaconsV1.calculate_position:input_type -> beacons_v1.BeaconV1PositionRequest
	7,  // 20: beacons_v1.BeaconsV1.get_beacons:output_type -> beacons_v1.BeaconV1PageReply
	12, // 21: beacons_v1.BeaconsV1.get_beacon_by_id:output_type -> beacons_v1.BeaconV1ObjectReply
	12, // 22: beacons_v1.BeaconsV1.create_beacon:output_type -> beacons_v1.BeaconV1ObjectReply
	12, // 23: beacons_v1.BeaconsV1.update_beacon:output_type -> beacons_v1.BeaconV1ObjectReply
	12, // 24: beacons_v1.BeaconsV1.delete_beacon_by_id:output_type -> beacons_v1.BeaconV1ObjectReply
	12, // 25: beacons_v1.BeaconsV1.get_beacon_by_udi:output_type -> beacons_v1.BeaconV1ObjectReply
	13, // 26: beacons_v1.BeaconsV1.calculate_position:output_type -> beacons_v1.BeaconV1PositionReply
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_protos_beacons_v1_proto_init() }
func file_protos_beacons_v1_proto_init() {
	if File_protos_beacons_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_beacons_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PagingParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoPointV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconV1Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconV1PageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconV1PageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconV1IdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconV1UdiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconV1PositionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconV1ObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconV1ObjectReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_beacons_v1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconV1PositionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_beacons_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_beacons_v1_proto_goTypes,
		DependencyIndexes: file_protos_beacons_v1_proto_depIdxs,
		MessageInfos:      file_protos_beacons_v1_proto_msgTypes,
	}.Build()
	File_protos_beacons_v1_proto = out.File
	file_protos_beacons_v1_proto_rawDesc = nil
	file_protos_beacons_v1_proto_goTypes = nil
	file_protos_beacons_v1_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BeaconsV1Client is the client API for BeaconsV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BeaconsV1Client interface {
	GetBeacons(ctx context.Context, in *BeaconV1PageRequest, opts ...grpc.CallOption) (*BeaconV1PageReply, error)
	GetBeaconById(ctx context.Context, in *BeaconV1IdRequest, opts ...grpc.CallOption) (*BeaconV1ObjectReply, error)
	CreateBeacon(ctx context.Context, in *BeaconV1ObjectRequest, opts ...grpc.CallOption) (*BeaconV1ObjectReply, error)
	UpdateBeacon(ctx context.Context, in *BeaconV1ObjectRequest, opts ...grpc.CallOption) (*BeaconV1ObjectReply, error)
	DeleteBeaconById(ctx context.Context, in *BeaconV1IdRequest, opts ...grpc.CallOption) (*BeaconV1ObjectReply, error)
	GetBeaconByUdi(ctx context.Context, in *BeaconV1UdiRequest, opts ...grpc.CallOption) (*BeaconV1ObjectReply, error)
	CalculatePosition(ctx context.Context, in *BeaconV1PositionRequest, opts ...grpc.CallOption) (*BeaconV1PositionReply, error)
}

type beaconsV1Client struct {
	cc grpc.ClientConnInterface
}

func NewBeaconsV1Client(cc grpc.ClientConnInterface) BeaconsV1Client {
	return &beaconsV1Client{cc}
}

func (c *beaconsV1Client) GetBeacons(ctx context.Context, in *BeaconV1PageRequest, opts ...grpc.CallOption) (*BeaconV1PageReply, error) {
	out := new(BeaconV1PageReply)
	err := c.cc.Invoke(ctx, "/beacons_v1.BeaconsV1/get_beacons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconsV1Client) GetBeaconById(ctx context.Context, in *BeaconV1IdRequest, opts ...grpc.CallOption) (*BeaconV1ObjectReply, error) {
	out := new(BeaconV1ObjectReply)
	err := c.cc.Invoke(ctx, "/beacons_v1.BeaconsV1/get_beacon_by_id", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconsV1Client) CreateBeacon(ctx context.Context, in *BeaconV1ObjectRequest, opts ...grpc.CallOption) (*BeaconV1ObjectReply, error) {
	out := new(BeaconV1ObjectReply)
	err := c.cc.Invoke(ctx, "/beacons_v1.BeaconsV1/create_beacon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconsV1Client) UpdateBeacon(ctx context.Context, in *BeaconV1ObjectRequest, opts ...grpc.CallOption) (*BeaconV1ObjectReply, error) {
	out := new(BeaconV1ObjectReply)
	err := c.cc.Invoke(ctx, "/beacons_v1.BeaconsV1/update_beacon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconsV1Client) DeleteBeaconById(ctx context.Context, in *BeaconV1IdRequest, opts ...grpc.CallOption) (*BeaconV1ObjectReply, error) {
	out := new(BeaconV1ObjectReply)
	err := c.cc.Invoke(ctx, "/beacons_v1.BeaconsV1/delete_beacon_by_id", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconsV1Client) GetBeaconByUdi(ctx context.Context, in *BeaconV1UdiRequest, opts ...grpc.CallOption) (*BeaconV1ObjectReply, error) {
	out := new(BeaconV1ObjectReply)
	err := c.cc.Invoke(ctx, "/beacons_v1.BeaconsV1/get_beacon_by_udi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconsV1Client) CalculatePosition(ctx context.Context, in *BeaconV1PositionRequest, opts ...grpc.CallOption) (*BeaconV1PositionReply, error) {
	out := new(BeaconV1PositionReply)
	err := c.cc.Invoke(ctx, "/beacons_v1.BeaconsV1/calculate_position", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeaconsV1Server is the server API for BeaconsV1 service.
type BeaconsV1Server interface {
	GetBeacons(context.Context, *BeaconV1PageRequest) (*BeaconV1PageReply, error)
	GetBeaconById(context.Context, *BeaconV1IdRequest) (*BeaconV1ObjectReply, error)
	CreateBeacon(context.Context, *BeaconV1ObjectRequest) (*BeaconV1ObjectReply, error)
	UpdateBeacon(context.Context, *BeaconV1ObjectRequest) (*BeaconV1ObjectReply, error)
	DeleteBeaconById(context.Context, *BeaconV1IdRequest) (*BeaconV1ObjectReply, error)
	GetBeaconByUdi(context.Context, *BeaconV1UdiRequest) (*BeaconV1ObjectReply, error)
	CalculatePosition(context.Context, *BeaconV1PositionRequest) (*BeaconV1PositionReply, error)
}

// UnimplementedBeaconsV1Server can be embedded to have forward compatible implementations.
type UnimplementedBeaconsV1Server struct {
}

func (*UnimplementedBeaconsV1Server) GetBeacons(context.Context, *BeaconV1PageRequest) (*BeaconV1PageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBeacons not implemented")
}
func (*UnimplementedBeaconsV1Server) GetBeaconById(context.Context, *BeaconV1IdRequest) (*BeaconV1ObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBeaconById not implemented")
}
func (*UnimplementedBeaconsV1Server) CreateBeacon(context.Context, *BeaconV1ObjectRequest) (*BeaconV1ObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBeacon not implemented")
}
func (*UnimplementedBeaconsV1Server) UpdateBeacon(context.Context, *BeaconV1ObjectRequest) (*BeaconV1ObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBeacon not implemented")
}
func (*UnimplementedBeaconsV1Server) DeleteBeaconById(context.Context, *BeaconV1IdRequest) (*BeaconV1ObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBeaconById not implemented")
}
func (*UnimplementedBeaconsV1Server) GetBeaconByUdi(context.Context, *BeaconV1UdiRequest) (*BeaconV1ObjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBeaconByUdi not implemented")
}
func (*UnimplementedBeaconsV1Server) CalculatePosition(context.Context, *BeaconV1PositionRequest) (*BeaconV1PositionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculatePosition not implemented")
}

func RegisterBeaconsV1Server(s *grpc.Server, srv BeaconsV1Server) {
	s.RegisterService(&_BeaconsV1_serviceDesc, srv)
}

func _BeaconsV1_GetBeacons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeaconV1PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconsV1Server).GetBeacons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beacons_v1.BeaconsV1/GetBeacons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconsV1Server).GetBeacons(ctx, req.(*BeaconV1PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconsV1_GetBeaconById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeaconV1IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconsV1Server).GetBeaconById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beacons_v1.BeaconsV1/GetBeaconById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconsV1Server).GetBeaconById(ctx, req.(*BeaconV1IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconsV1_CreateBeacon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeaconV1ObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconsV1Server).CreateBeacon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beacons_v1.BeaconsV1/CreateBeacon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconsV1Server).CreateBeacon(ctx, req.(*BeaconV1ObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconsV1_UpdateBeacon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeaconV1ObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconsV1Server).UpdateBeacon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beacons_v1.BeaconsV1/UpdateBeacon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconsV1Server).UpdateBeacon(ctx, req.(*BeaconV1ObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconsV1_DeleteBeaconById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeaconV1IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconsV1Server).DeleteBeaconById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beacons_v1.BeaconsV1/DeleteBeaconById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconsV1Server).DeleteBeaconById(ctx, req.(*BeaconV1IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconsV1_GetBeaconByUdi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeaconV1UdiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconsV1Server).GetBeaconByUdi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beacons_v1.BeaconsV1/GetBeaconByUdi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconsV1Server).GetBeaconByUdi(ctx, req.(*BeaconV1UdiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconsV1_CalculatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeaconV1PositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconsV1Server).CalculatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beacons_v1.BeaconsV1/CalculatePosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconsV1Server).CalculatePosition(ctx, req.(*BeaconV1PositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BeaconsV1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "beacons_v1.BeaconsV1",
	HandlerType: (*BeaconsV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_beacons",
			Handler:    _BeaconsV1_GetBeacons_Handler,
		},
		{
			MethodName: "get_beacon_by_id",
			Handler:    _BeaconsV1_GetBeaconById_Handler,
		},
		{
			MethodName: "create_beacon",
			Handler:    _BeaconsV1_CreateBeacon_Handler,
		},
		{
			MethodName: "update_beacon",
			Handler:    _BeaconsV1_UpdateBeacon_Handler,
		},
		{
			MethodName: "delete_beacon_by_id",
			Handler:    _BeaconsV1_DeleteBeaconById_Handler,
		},
		{
			MethodName: "get_beacon_by_udi",
			Handler:    _BeaconsV1_GetBeaconByUdi_Handler,
		},
		{
			MethodName: "calculate_position",
			Handler:    _BeaconsV1_CalculatePosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/beacons_v1.proto",
}
